[package]
name = "billion-rows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
fxhash = "0.2.1"
libc = "0.2.152"
